version: 0.0
os: linux
files:
  - source: ./
    destination: ./
hooks:
ApplicationStop:
   - location: killall node
     timeout: 10
     runas: ubuntu
  ApplicationStart:
    - location: start.sh
      timeout: 6
      runas: ubuntu
