version: 0.1

phases:
  install:
    commands:
      - npm install
      - sudo npm install -g mocha
  pre_build:
    commands:
      - mocha
      - sudo rm -r node_modules
  build:
    commands:
      - echo BUILD
      - npm install --production
  post_build:
    commands:
      - echo DONE
